name: Deploy Azure Function
on:
  push:
    branches:
      - main
jobs:
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash    
      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set environment variables
        run: |
          echo "MONGOSTRING=${{ secrets.MONGOSTRING }}" >> $GITHUB_ENV
      - name: Deploy to Azure Functions
        run: |
          func azure functionapp publish gocroot
          